FROM node:alpine

# set user as 'node'
# The end result will be that all files and directories in the project will no longer be owned by root and will instead be owned by the node user.
USER node

# create folder for node user
RUN mkdir -p /home/node/app/node_modules
WORKDIR /home/node/app

# The inline chown commands will set ownership of the files you are copying from your local environment to the node user in the container.
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]